plugins.vlive: fix URL regex and plugin
streamlink/streamlink pull request #3315
Opened 2020-11-02 14:38 UTC by SeonjaeHyeon

closes #3314 

The site was completely revised recently and url format was changed.
But old format still exists, so I added support for both formats.

2020-11-02 15:45 UTC, mkbloke commented
I was just looking at this myself.  One thing I noticed is that the literal dot after www in the URL regex needs escaping, although that was present before your changes.

I know you've just followed what was previously done in the existing plugin, but it's possible when one of the main Streamlink devs reviews your code that you could be asked to change the `raise PluginError()`s to `log.error()`s and then return.  At least, that seems to be the way they prefer that I have seen.  I'm sure you'll find out soon enough from one of them though.

2020-11-02 16:01 UTC, bastimeyer commented on src/streamlink/plugins/vlive.py
> +            streams[i['streamName']] = res_streams.popitem()[1]
Just yielding a tuple of the stream name and HLSStream instance is cleaner than adding them to a dict and returning it afterwards, but that's just a "cosmetic" code suggestion.

2020-11-02 16:02 UTC, bastimeyer commented on src/streamlink/plugins/vlive.py
> +            raise PluginError('Could not find page info')
Unavailable streams are not supposed to raise a PluginError. Just return None or an empty dict. PluginErrors are meant for actual errors. Same issue below...

2020-11-03 12:45 UTC, SeonjaeHyeon commented
I appreciate your help. @mkbloke @bastimeyer 

I modified PR as you suggested to me.
But I'm not familiar with using schemas and yield, I'm not sure it is correct.

Plus, you can find Live streams here: https://www.vlive.tv/home/new?lang=en (it will be redirected to english page)
And you will see two types of video, Live and replay.
The live video has LIVE sign on thumbnail. Maybe you can find it easily.
There might be no live videos when you check the site due to time difference.

2020-11-04 19:51 UTC, back-to commented on src/streamlink/plugins/vlive.py
> +    _url_re = re.compile(r"https?://(?:www\.)vlive\.tv/(?P<format>video|post)/(?P<id>[0-9\-]+)")
```suggestion
    _url_re = re.compile(r"https://www\.vlive\.tv/(?P<format>video|post)/(?P<id>[0-9\-]+)")
```
if there is only https support you don't need to ignore the `s`
same for the `www` subdomain

2020-11-04 19:51 UTC, back-to commented on src/streamlink/plugins/vlive.py
> +        url_format, video_id = re.match(self._url_re, self.url).group('format', 'id')
```suggestion
        url_format, video_id = self._url_re.match(self.url).groups()
```

you don't need `re.`

2020-11-06 00:34 UTC, bastimeyer reviewed
Code-wise, this is looking good now. I still don't see any live streams on this site though, so I can't verify it.

2020-11-06 00:35 UTC, bastimeyer approved these changes

2020-11-06 00:51 UTC, gravyboat commented
I'd like to see examples of actual live streams. I checked yesterday and today and didn't see anything live that I could actually watch. It just looks like the equivalent of a blogging platform. How often are there live streams? Where can these streams be viewed? Are the streams geo locked? Until these questions are answered this PR should not be merged, and if these questions cannot be answered and it's simply for watching VODs or live streams of pre-recorded content the plugin should instead be removed.

2020-11-06 00:51 UTC, gravyboat requested changes
See my above comment.

2020-11-06 04:36 UTC, SeonjaeHyeon commented
> I'd like to see examples of actual live streams. I checked yesterday and today and didn't see anything live that I could actually watch. It just looks like the equivalent of a blogging platform.

As I said above, I think you have time difference problem. This site is a South Korean live streaming platform and many korean celebrities broadcast live videos. So, you should check the site considering korea time (GMT +9).

> How often are there live streams?

Because most live broadcasts are irregular, all I can say is, there were some live videos between evening and midnight.

And now, I can see two live videos.
https://imgur.com/xA5vsNO

> Where can these streams be viewed?

You can see the live videos the New page: https://www.vlive.tv/home/new?lang=en
or, on particular channel, check Star Board page.

> Are the streams geo locked?

I don't think they are geo-blocked. Fans from all over the world watch and chat when their celebrities broadcast.

2020-11-06 16:55 UTC, back-to requested changes

2020-11-06 16:55 UTC, back-to commented on src/streamlink/plugins/vlive.py
> +            validate.get("postDetail"),
you need to cache the errors

```
[cli][info] Found matching plugin vlive for URL https://www.vlive.tv/video/222194
error: Unable to validate response text: <re.Match object; span=(3665, 6426), match='window.__PRELOADED_STATE__={"common":{"userCountr> does not equal None or Unable to validate key 'postDetail': Key 'post' not found in 
{
    'error': {
        'errorCode': 'common_700',
        'message': 'Only members of this channel can continue. \nJoin 온앤오프 (ONF) channel!',
        'data': {
            'url': 'https://vlive.tv/post/0-19795109',
            'title': '안뇽 퓨즈🌙',
            'createdAt': 1604680573000,
            'availableActions': [],
            'commentCount': 0,
            'emotionCount': 0,
            'postId': '0-19795109',
            'isCommentEnabled': True,
            'officialVideo': {
                'videoSeq': 222194,
                'type': 'LIVE',
                'title': '안뇽 퓨즈🌙',
                'multinationalTitles': [{
                    'type': 'VIDEO_TITLE',
                    'seq': 222194,
                    'locale': 'ko_KR',
                    'label': '안뇽 퓨즈🌙',
                    'defaultYn': True
                }],
                'playCount': 0,
                'likeCount': 387749,
                'commentCount': 7470,
                'thumb': 'http://thumb.vlive.tv/live/222194/thumb',
                'exposeStatus': 'EXPOSED',
                'screenOrientation': 'HORIZONTAL',
                'willStartAt': 1604680572000,
                'onAirStartAt': 1604680573000,
                'willEndAt': 1604681498000,
                'createdAt': 1604680572000,
                'liveThumbYn': False,
                'upcomingYn': False,
                'productType': 'NONE',
                'preAdYn': True,
                'postAdYn': False,
                'mobileDAYn': True,
                'vrContentType': 'NONE',
                'schemaVersion': 'V202009',
                'liveType': 'GENERAL',
                'status': 'ENDED',
                'startAt': 1604680591000,
                'endAt': 1604681498000,
                'watchedCount': 9813,
                'publicYn': False,
                'userSeq': 14376571,
                'momentable': False
            },
            'contentType': 'VIDEO',
            'author': {
                'memberId': 'a6261a101b7192d90942867e6027dde3',
                'channelCode': 'E812E3',
                'joined': True,
                'nickname': 'Staff_온앤오프 (ONF)',
                'profileImageUrl': 'http://v.phinf.naver.net/20200808_114/1596822845075mGyrT_PNG/profile370_83164.png',
                'officialProfileType': 'STAFF'
            },
            'channel': {
                'channelCode': 'E812E3',
                'channelName': '온앤오프 (ONF)'
            },
            'board': {
                'boardId': 7020,
                'title': '[ONF FUSE 1ST] Star Board',
                'boardType': 'STAR',
                'payRequired': True,
                'readAllowedLabel': 'Who purchased ONF OFFICIAL FANSHIP FUSE 1ST'
            }
        }
    },
    'onLoading': False
}
```

2020-11-08 16:38 UTC, merged