plugins.twitcasting: add support for private/password-protected streams
streamlink/streamlink pull request #3505
Opened 2021-01-22 21:03 UTC by alnj

### Description
Add a `--twitcasting-password` option to the TwitCasting plugin, supporting private (password-protected) TwitCasting streams.

closes #3504

### How it works
If the command line option is used, then we append `&word={md5_encrypted_password}` to `real_stream_url`.

### How to test
You can easily start a livestream from Twitcasting by hovering the blue "Broadcast" button at the top right of the site then clicking "Web broadcasting". Scroll down to set a password then back up to start an audio-only livestream. If you do not have an account, you can quickly login with a Twitter or Facebook account if you have one.

This is my first ever pull request, in a language I have essentially no experience with. I hope everything is OK.

2021-01-22 21:29 UTC, mkbloke commented
Don't worry about the linting too much (the extra commits will be squashed), but just in case you didn't know, you can install the dev-requirements and then run flake8 locally to get it right on your initial PR: https://streamlink.github.io/developing.html

2021-01-23 02:17 UTC, bastimeyer requested changes
Just reviewing the code changes, not the actual password implementation because I don't want to create an account and create a stream for this site.

> This is my first ever pull request, in a language I have essentially no experience with. I hope everything is OK.

No problem. If you need help, just ask.

2021-01-23 08:18 UTC, alnj commented
Thanks for the review! I've committed the changes you suggested and made sure that the option still works. No problem with it on my end.

2021-01-23 10:12 UTC, bastimeyer approved these changes
Code changes are looking good now. As said, this is just a code review and I can't tell whether this is the correct implementation, because I didn't validate it.

As a potential improvement, if the site returns an error response for wrong passwords, this could be caught here and handled with a respective error message. Tests for the newly added plugin argument are not really needed, as the plugin's stream URL resolving logic isn't tested anyway.

To the one who merges this, please make sure that no \@-mentions are included in the squashed commit message body, thanks.

2021-01-30 06:25 UTC, merged