plugins.vk: add support for WAF cookie
streamlink/streamlink pull request #4638
Opened 2022-07-04 18:15 UTC by mkbloke

Also corrected the API POST `params`/`data` dicts.

closes #4637

2022-07-05 15:11 UTC, bastimeyer reviewed
The first URL from the tests is returning this:

> ```
> $ streamlink 'https://vk.com/video-9944999_456239622' best -l debug
> ...
> [plugins.vk][debug] Saved cookie not found.
> [plugins.vk][info] Getting new cookie.
> error: Unable to open URL: https://vk.com/429.html?hash429=wMF4IzvUyM5acpz9RUB7S4wasLQWDuHjX7ptYhUSQedbwJd8ViiIDIUF4MapFBvaDBhxzkauoVfsYbzXN5VPlqMwIaoPMD2aWbxtyC4GCp1JMgkjuRc6&redirect429=/&key=87477569783524fc736506c9a64450f4 (429 Client Error: Too Many Requests for url: https://vk.com/)
> ```

2022-07-05 15:11 UTC, bastimeyer commented on src/streamlink/plugins/vk.py
> +        res = self.session.http.get(f"{res.url}&key={key}")
The `res` var is unused.

Setting the `key` parameter on the `params` keyword is also better than modifying the request URL.

Also, if you want to make mypy happy, then return False where you currently return None (the linting rule is currently disabled, hence why there's no failure).

2022-07-06 23:49 UTC, bastimeyer requested changes
Don't add hooks to the entire HTTP session. This is bad.

That should do the trick:

```diff
diff --git a/src/streamlink/plugins/vk.py b/src/streamlink/plugins/vk.py
index 33a6365c..c72e9458 100644
--- a/src/streamlink/plugins/vk.py
+++ b/src/streamlink/plugins/vk.py
@@ -14,6 +14,7 @@ from streamlink.plugin import Plugin, PluginError, pluginmatcher
 from streamlink.plugin.api import validate
 from streamlink.stream.dash import DASHStream
 from streamlink.stream.hls import HLSStream
+from streamlink.utils.url import update_qsd
 
 log = logging.getLogger(__name__)
 
@@ -29,24 +30,25 @@ class VK(Plugin):
     HASH_COOKIE = "hash429"
     SOLUTION_COOKIE = "solution429"
 
-    def check_for_waf(self, res, **kwargs):
-        if res.headers.get("X-WAF-Backend-Status") == "challenge_success" and hasattr(self, "original_request"):
-            self.session.http.cookies.update(res.cookies)
-            self.session.http.cookies.pop(self.HASH_COOKIE, None)
-            self.original_request.headers.pop("Cookie", None)
-            self.original_request.prepare_cookies(self.session.http.cookies)
-            res = self.session.http.send(self.original_request)
-            del self.original_request
-            self.save_cookies(cookie_filter=lambda c: c.name == self.SOLUTION_COOKIE)
-            return res
-
-        if res.status_code == 302 and res.cookies.get(self.HASH_COOKIE):
-            log.debug("Getting new WAF cookie")
-            cookie = res.cookies.get(self.HASH_COOKIE)
-            key = md5(cookie.encode("utf-8")).hexdigest()
-            res.headers["Location"] = f"{res.headers['Location']}&key={key}"
-            self.original_request = res.request
-            return res
+    def _get_cookies(self):
+        if self.session.http.cookies.get(self.SOLUTION_COOKIE, domain=".vk.com"):
+            log.debug("Using cached WAF cookie")
+            return
+
+        def on_response(res, **kwargs):
+            if res.headers.get("x-waf-redirect") == "1":
+                if not res.headers.get("X-WAF-Backend-Status"):
+                    log.debug("Getting new WAF cookie")
+                    cookie = res.cookies.get(self.HASH_COOKIE)
+                    key = md5(cookie.encode("utf-8")).hexdigest()
+                    res.headers["Location"] = update_qsd(res.headers["Location"], qsd={"key": key})
+                    return res
+                elif res.headers.get("X-WAF-Backend-Status") == "challenge_success":
+                    self.session.http.cookies.update(res.cookies)
+                    self.save_cookies(cookie_filter=lambda c: c.name == self.SOLUTION_COOKIE)
+                    return res
+
+        self.session.http.get("https://vk.com/", hooks={"response": on_response})
 
     def _has_video_id(self):
         return any(m for m in self.matches[:-1])
@@ -78,8 +80,7 @@ class VK(Plugin):
         raise NoStreamsError(self.url)
 
     def _get_streams(self):
-        self.session.http.hooks["response"] = self.check_for_waf
-
+        self._get_cookies()
         self.follow_vk_redirect()
 
         video_id = self.match.group("video_id")
```

2022-07-07 01:10 UTC, mkbloke commented
One of the reasons for some of the logic I put into the original code is that it didn't require an initial probe.  Some of the other logic was to handle the case that if you change IP address (or maybe region, who knows, but the latter can happen if you're a VPN user), an existing `solution429` cookie becomes invalid and will need replacing.  This scenario now fails with the code above.

2022-07-07 01:25 UTC, bastimeyer commented
Just make the initial request every time, and don't store the cookie, as it's unnecessary.

2022-07-07 07:38 UTC, bastimeyer commented
The `self.session.http.cookies.update(res.cookies)` on `res.headers.get("X-WAF-Backend-Status") == "challenge_success"` should be redundant, as `requests` will update the session cookies after the hook has been executed anyway. Unfortunately, I don't get the cookie requirement right now, so I can't check. Doesn't matter though, going to merge.

2022-07-07 07:40 UTC, merged