plugin.tf1: implement authentification
streamlink/streamlink pull request #5983
Opened 2024-05-09 14:14 UTC by BellezaEmporium

This PR is aimed to provide authentification basis for the website TF1.fr. A step forward would be to check the user subscriptions, ad now certain streams might be pay-per-view, under the TF1MAX subscription plan.

With recommendations from @bastimeyer earlier on, on issue 5379, I've rewrote the plugin to make sure it suits the standards.

2024-05-09 19:02 UTC, bastimeyer requested changes
Thanks for the PR.

I'm just going to comment on the code. I currently don't have time to check the site and validate your plugin changes, including anything related to authentication and HTTP requests+responses.

There are also tons of linting issues which you'll have to fix. Please have a look at this short guide:
https://streamlink.github.io/developing.html

Also one question since I'm unaware of the account restrictions: the plugin covers multiple sites. Is authentication required for of them?

2024-05-09 19:38 UTC, BellezaEmporium commented
Thanks for the comments. I'll get through them one by one and fix the necessary issues.

2024-05-09 19:50 UTC, BellezaEmporium commented on src/streamlink/plugins/tf1.py
> +                    "consent_ids": ["1", "2", "3", "4", "10001", "10003", "10005", "10007", "10013", "10015", "10017", "10019", "10009", "10011", "13002", "13001", "10004", "10014", "10016", "10018",
The consent_ids are linked to Gigya's API, a sort of link between the website and their services. While there's no documentation talking about it, You can find them when trying to make a connection to https://tf1.fr. The source code should give you "neededConsentIds".

Like in this example : 
![image](https://github.com/streamlink/streamlink/assets/30985701/0d7a38ea-4f76-4c9f-ae13-75afdc8dd9f6)

The one I've added in this code / PR is from my own attempt at connecting using my personal account to tf1.fr.

2024-05-15 13:20 UTC, BellezaEmporium commented
I've rewrote the plugin based on your recommendations. Last commit should reflect all the changes given.

2024-05-17 21:00 UTC, bastimeyer commented
I force-pushed onto your PR branch because I decided to clean up the remaining issues myself and make a couple more changes.

- Fixed linting and code style issues
- Fixed missing `$account` plugin-metadata
- Fixed error handling
- Fixed validation schemas
- Fixed auth logic issues
- Renamed `--tf1-username` to `--tf1-email`
- Added token caching and `--tf1-purge-credentials`

----

Authentication is only required on `tf1.fr`. The other sites work fine, even without a French IP address:

```
$ streamlink https://tf1info.fr/direct/ best
[cli][info] Found matching plugin tf1 for URL https://tf1info.fr/direct/
[cli][info] Available streams: 234p (worst), 360p, 576p_alt, 576p, 720p (best)
[cli][info] Opening stream: 720p (hls-multi)
[cli][info] Starting player: /usr/bin/mpv
[utils.named_pipe][info] Creating pipe streamlinkpipe-153664-1-5029
[utils.named_pipe][info] Creating pipe streamlinkpipe-153664-2-3929
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...

$ streamlink https://www.lci.fr/direct best
[cli][info] Found matching plugin tf1 for URL https://www.lci.fr/direct
[cli][info] Available streams: 234p (worst), 360p, 576p_alt, 576p, 720p (best)
[cli][info] Opening stream: 720p (hls-multi)
[cli][info] Starting player: /usr/bin/mpv
[utils.named_pipe][info] Creating pipe streamlinkpipe-153955-1-8455
[utils.named_pipe][info] Creating pipe streamlinkpipe-153955-2-2202
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

New token with throwaway-account:

```
$ streamlink https://www.tf1.fr/tf1/direct best --http-proxy socks5h://localhost:1920 --tf1-email ogbeyafi@email1.io --tf1-password Qwerty123456789!
[cli][info] Found matching plugin tf1 for URL https://www.tf1.fr/tf1/direct
[plugins.tf1][info] Acquiring new user-authentication token...
[cli][info] Available streams: 234p (worst), 360p, 576p_alt, 576p, 720p (best)
[cli][info] Opening stream: 720p (hls-multi)
[cli][info] Starting player: /usr/bin/mpv
[utils.named_pipe][info] Creating pipe streamlinkpipe-154141-1-4629
[utils.named_pipe][info] Creating pipe streamlinkpipe-154141-2-6526
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

Cached token:

```
$ streamlink https://www.tf1.fr/tf1/direct best --http-proxy socks5h://localhost:1920
[cli][info] Found matching plugin tf1 for URL https://www.tf1.fr/tf1/direct
[cli][info] Available streams: 234p (worst), 360p, 576p_alt, 576p, 720p (best)
[cli][info] Opening stream: 720p (hls-multi)
[cli][info] Starting player: /usr/bin/mpv
[utils.named_pipe][info] Creating pipe streamlinkpipe-154271-1-2504
[utils.named_pipe][info] Creating pipe streamlinkpipe-154271-2-3907
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...

$ streamlink https://www.tf1.fr/stream/chante-69061019 best --http-proxy socks5h://localhost:1920
[cli][info] Found matching plugin tf1 for URL https://www.tf1.fr/stream/chante-69061019
[cli][info] Available streams: 234p (worst), 270p, 360p, 576p (best)
[cli][info] Opening stream: 576p (hls-multi)
[cli][info] Starting player: /usr/bin/mpv
[utils.named_pipe][info] Creating pipe streamlinkpipe-154476-1-4314
[utils.named_pipe][info] Creating pipe streamlinkpipe-154476-2-3647
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

Invalid auth data:

```
$ streamlink https://www.tf1.fr/tf1/direct best --http-proxy socks5h://localhost:1920 --tf1-purge-credentials --tf1-email ogbeyafi@email1.io --tf1-password invalid
[cli][info] Found matching plugin tf1 for URL https://www.tf1.fr/tf1/direct
[plugins.tf1][info] Removing cached user-authentication token...
[plugins.tf1][info] Acquiring new user-authentication token...
error: error_code=403042 - invalid loginID or password
```

2024-05-17 21:03 UTC, bastimeyer commented
The cache currently doesn't set an expiration time/date, but it's not really important...

Going to merge this now.

2024-05-17 21:04 UTC, merged

2024-05-18 09:36 UTC, BellezaEmporium commented
Perfect, thanks for going further in this PR. Interesting, thought they would enforce it everywhere. I consider myself corrected.

2024-05-18 17:51 UTC, octavioj commented
This is wonderful. Which version of streamline will have this modification, if I may ask?

2024-05-18 18:00 UTC, bastimeyer commented
`6.7.4+1.g7adb5b12`
https://github.com/streamlink/streamlink/commits/master/

2024-05-18 18:02 UTC, octavioj commented
Thank you.

2024-05-18 22:01 UTC, campones commented
I tested few hours ago the beta release from yesterday, works perfectly

2024-05-19 20:27 UTC, octavioj commented
It works wonderfully with liveproxy too. Excellent.

2024-05-19 23:21 UTC, campones commented
@octavioj sorry for the off topic but what's the point to use this liveproxy exactly?

2024-05-19 23:31 UTC, BellezaEmporium commented
That's not the correct place to talk about this I believe.

2024-05-19 23:34 UTC, campones commented
probably not. anyway, good job guys,  has been quite a long way but result is outstanding ;)